
server:
  port: ${PORT}

  #ssl
  ssl:
    enabled: true
    key-store: classpath:${KEY-PATH}
    key-store-password: ${KEY-PASS}
    key-store-type: PKCS12
    key-alias: ${KEY-ALIAS}
    
spring:
  cache:
    type: redis
  config:
    activate:
      on-profile: prod
  redis:
    host: ${REDISDB-HOST-PROD}
    password: ${REDISDB-PASSWORD-PROD}
    port: ${REDISDB-PORT-PROD}

  # Mysql Database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://${MYSQLDB-URL}/${MYSQLDB-NAME-PROD}?useUnicode=true&serverTimezone=Asia/Seoul'
    username: ${MYSQLDB-USERNAME-PROD}
    password: ${MYSQLDB-PASSWORD-PROD}

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none        # DB 테이블 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true      #
        show_sql: true        #


toki:
  config:
    cors:
      allowed-origins: ${CORS-ALLOWED-ORIGINS-PROD}

logging:
  level:
    web: error
    sql: error


